name: Run My Pipeline

on:
  schedule:
    - cron: '0 */3 * * *'  # every 3 hours
  workflow_dispatch:  # allows manual trigger

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        python -m textblob.download_corpora
        python -m nltk.downloader stopwords punkt vader_lexicon

    - name: Run sentiment pipeline
      run: python nlpai_tweets.py

    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --staged --quiet || git commit -m "Updated data on $(date)"
        git push
