name: Run My Pipeline

on:
  schedule:
    - cron: '0 */3 * * *'  # every 3 hours
  workflow_dispatch:  

permissions:
  contents: write  

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  
      with:
        token: ${{ secrets.GH_PAT }} 

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        python -m textblob.download_corpora
        python -m nltk.downloader stopwords punkt vader_lexicon

    - name: Run sentiment pipeline
      run: python nlpai_tweets.py

    - name: Commit and push results
      env:
        TOKEN: ${{ secrets.GH_PAT }}  
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
        git add -A
        git diff --staged --quiet || git commit -m "Updated data on $(date)"
        git push
